name: "sway-goldsky"
api_version: "reorg-handling"
secrets:
  - PRIVATE_ESCROW_OWNER_KEY 
tasks:
  - path: "./src/tasks/oracle.ts"
    name: "oracle"
    triggers: 
      - type: "http"
        authentication: "auth_token"
